version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: controle_acesso_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controle_acesso
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: controle_acesso_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: controle_acesso
      JWT_SECRET: hdf78sd8f7sd8f7sd8fsd8fsd8fsd8f
      JWT_EXPIRES_IN: 1d
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
